[plugin]
name = "docker-plugin-hipchat"
description = "Sends HipChat notifications"
version = "1.0"
maintainer_name = "Lajos Papp"
maintainer_email = "lajos.papp@sequenceiq.com"
website_url = "http://github.com/lalyos/docker-plugin-hipchat"

[plugin.config]
message_format = "message template in jq style"

[plugin.compatibility]
